spring:
  application:
    name: reactivecommons
  data:
    mongodb:
      uri: mongodb+srv://prueba:prueba@cluster0.dwhig.mongodb.net/test?authSource=admin&replicaSet=atlas-wkuhs8-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true
      database: reactivecommons
  rabbitmq:
    #host: 8.8.8.1
    host: 127.0.0.1
    #port: 5729
    port: 5672
    username: guest
    password: guest